# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-04 18:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='forbidden',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rude_words', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('contant', models.TextField()),
                ('user_reply', models.TextField()),
                ('post_time', models.DateTimeField(verbose_name='datetime')),
                ('post_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='geeks.category')),
            ],
        ),
    ]
