# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-06 09:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geeks', '0003_auto_20170206_1147'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='post_image',
            field=models.ImageField(default=b'No_image_available.svg', upload_to=b'imgs/'),
        ),
    ]
