# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-06 10:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('geeks', '0004_post_post_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Comment_contant', models.TextField()),
                ('user_reply', models.TextField()),
                ('post_comment_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='geeks.Post')),
            ],
        ),
        migrations.RemoveField(
            model_name='reply',
            name='post_reply',
        ),
        migrations.DeleteModel(
            name='Reply',
        ),
    ]
