# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-07 08:16
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geeks', '0005_auto_20170206_1253'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Admin',
        ),
        migrations.DeleteModel(
            name='users',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='Comment_contant',
            new_name='comment_contant',
        ),
        migrations.AddField(
            model_name='comment',
            name='comment_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 2, 7, 10, 16, 52, 253098)),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_image',
            field=models.ImageField(default=b'imgs/No_Image.jpg', upload_to=b'imgs/'),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_time',
            field=models.DateTimeField(default=datetime.datetime(2017, 2, 7, 10, 16, 52, 252477)),
        ),
    ]
